import _l from 'lib/i18n';

let Common = {
  initAccountLabels: [
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`Name`,
      fieldLabel: 'Company Name',
      dbColName: 'accountName',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`VAT number`,
      fieldLabel: 'VAT Number',
      dbColName: 'accountVat',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`Phone`,
      fieldLabel: 'Company Phone',
      dbColName: 'accountPhone',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`Email`,
      fieldLabel: 'Company Email',
      dbColName: 'accountEmail',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`Street`,
      fieldLabel: 'Company Street',
      dbColName: 'accountStreet',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`Zip code`,
      fieldLabel: 'Company Zip Code',
      dbColName: 'accountZipCode',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`City`,
      fieldLabel: 'Company City',
      dbColName: 'accountCity',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`Region/State`,
      fieldLabel: 'Company Region/State',
      dbColName: 'accountState',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`Country`,
      fieldLabel: 'Company Country',
      dbColName: 'accountCountry',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`Type`,
      fieldLabel: 'Company Type',
      dbColName: 'accountType',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`Industry`,
      fieldLabel: 'Company Industry',
      dbColName: 'accountIndustry',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`Size`,
      fieldLabel: 'Company Size',
      dbColName: 'accountSize',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`Web`,
      fieldLabel: 'Company Web',
      dbColName: 'accountWeb',
    },
    {
      vis: true,
      inGroup: 'account',
      viewLabel: _l`Note`,
      fieldLabel: 'Company Note',
      dbColName: 'accountNote',
    },
  ],
  initContactLabels: [
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`First Name`,
      fieldLabel: 'Contact Firstname',
      dbColName: 'contactFirstName',
    },
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`Last Name`,
      fieldLabel: 'Contact Lastname',
      dbColName: 'contactLastName',
    },
    //{
    //    'vis': true,
    //    'inGroup': 'contact',
    //    'viewLabel': 'Behaviour Profile',
    //    'fieldLabel': 'Contact Behaviour Profile',
    //    'dbColName': 'contactBehaviourProfile'
    //},
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`Phone`,
      fieldLabel: 'Contact Phone',
      dbColName: 'contactPhone',
    },
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`Email`,
      fieldLabel: 'Contact Email',
      dbColName: 'contactEmail',
    },
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`Street`,
      fieldLabel: 'Contact Street',
      dbColName: 'contactStreet',
    },
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`Zip code`,
      fieldLabel: 'Contact Zip code',
      dbColName: 'contactZipCode',
    },
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`City`,
      fieldLabel: 'Contact City',
      dbColName: 'contactCity',
    },
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`Region/State`,
      fieldLabel: 'Contact Region/State',
      dbColName: 'contactState',
    },
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`Country`,
      fieldLabel: 'Contact Country',
      dbColName: 'contactCountry',
    },
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`Title`,
      fieldLabel: 'Contact Title',
      dbColName: 'contactTitle',
    },
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`Type`,
      fieldLabel: 'Contact Type',
      dbColName: 'contactType',
    },
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`Industry`,
      fieldLabel: 'Contact Industry',
      dbColName: 'contactIndustry',
    },
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`Relation`,
      fieldLabel: 'Contact Relation',
      dbColName: 'contactRelation',
    },
    //{
    //    'vis': true,
    //    'inGroup': 'contact',
    //    'viewLabel': 'Relationship',
    //    'fieldLabel': 'Contact Relationship',
    //    'dbColName': 'contactRelationship'
    //},
    {
      vis: true,
      inGroup: 'contact',
      viewLabel: _l`Note`,
      fieldLabel: 'Contact Note',
      dbColName: 'contactNote',
    },
  ],
  initLeadLabels: [
    {
      vis: true,
      inGroup: 'lead',
      viewLabel: _l`Note`,
      fieldLabel: 'Note',
      dbColName: 'leadnote',
    },
  ],
};
export default Common;
