// @flow
import { fork } from 'redux-saga/effects';
import authSaga from 'components/Auth/auth.saga';
import delegationSaga from 'components/Delegation/delegation.saga';
import categorySaga from 'components/Category/category.saga';
import tagSaga from 'components/Tag/tag.saga';
import taskSaga from 'components/Task/task.saga';
import leadSaga from 'components/Lead/lead.saga';
import contactSaga from 'components/Contact/contact.saga';
import callListContactSaga from 'components/CallListContact/callListContact.saga';
import callListAccountSaga from 'components/CallListAccount/callListAccount.saga';
import organisationSaga from 'components/Organisation/organisation.saga';
import userSaga from 'components/User/user.saga';
import unitSaga from 'components/Unit/unit.saga';
import appSaga from 'components/App/app.saga';
import profileSaga from 'components/Profile/profile.saga';
import settingsSaga from 'components/Settings/settings.saga';
import industrySaga from 'components/Industry/industry.saga';
import focusSaga from 'components/Focus/focus.saga';
import typeSaga from 'components/Type/type.saga';
import sizeSaga from 'components/Size/size.saga';
import prospectSaga from 'components/Prospect/prospect.saga';
import notificationSaga from 'components/Notification/notification.saga';
import advancedSearchSaga from 'components/AdvancedSearch/advanced-search.saga';
import customFieldSaga from 'components/CustomField/custom-field.saga';
import multiRelationSaga from 'components/MultiRelation/multi-relation.saga';
import salesMethodSaga from 'components/SalesMethod/sales-method.saga';
import appointmentSaga from 'components/Appointment/appointment.saga';
import insightSaga from 'components/Insight/insight.saga';
import dashboardSaga from 'components/Dashboard/dashboard.saga';
import measurementTypeSaga from 'components/MeasurementType/measurement-type.saga';
import lineOfBusinessSaga from 'components/LineOfBusiness/line-of-business.saga';
import productSaga from 'components/Product/product.saga';
import productGroupSaga from '../components/ProductGroup/productGroup.saga';
import wizardSaga from 'components/Wizard/wizard.saga';
import unqualifiedDeal from 'components/PipeLineUnqualifiedDeals/unqualifiedDeal.saga';
import qualifiedDeal from 'components/PipeLineQualifiedDeals/qualifiedDeal.saga';
import commonSage from 'components/Common/common.saga';
import orderRow from 'components/OrderRow/order-row.saga';
import trelloSaga from '../components/PipeLineQualifiedDeals/TaskSteps/TrelloElement/trello-saga';
import resourcesSaga from 'components/Resources/resources.saga';
import recruitmentSaga from '../components/Recruitment/recruitment.saga';
import viettelSaga from '../components/Viettel/viettel.sagas';
import quotationSaga from '../components/Quotations/quotation.saga';

function* rootSaga(): Generator<*, *, *> {
  yield fork(authSaga);
  yield fork(delegationSaga);
  yield fork(categorySaga);
  yield fork(tagSaga);
  yield fork(taskSaga);
  yield fork(contactSaga);
  yield fork(appointmentSaga);
  yield fork(organisationSaga);
  yield fork(userSaga);
  yield fork(unitSaga);
  yield fork(leadSaga);
  yield fork(appSaga);
  yield fork(profileSaga);
  yield fork(settingsSaga);
  yield fork(industrySaga);
  yield fork(notificationSaga);
  yield fork(advancedSearchSaga);
  yield fork(focusSaga);
  yield fork(typeSaga);
  yield fork(sizeSaga);
  yield fork(customFieldSaga);
  yield fork(multiRelationSaga);
  yield fork(salesMethodSaga);
  yield fork(prospectSaga);
  yield fork(insightSaga);
  yield fork(dashboardSaga);
  yield fork(measurementTypeSaga);
  yield fork(lineOfBusinessSaga);
  yield fork(productSaga);
  yield fork(wizardSaga);
  yield fork(callListContactSaga);
  yield fork(callListAccountSaga);
  yield fork(unqualifiedDeal);
  yield fork(productGroupSaga);
  yield fork(qualifiedDeal);
  yield fork(commonSage);
  yield fork(orderRow);
  yield fork(trelloSaga);
  yield fork(resourcesSaga);
  yield fork(recruitmentSaga);
  yield fork(viettelSaga);
  yield fork(quotationSaga);
}

export default rootSaga;
